title: Personal Portfolio Tracker
description: 跨券商 · 多币种 · 自动价格与汇率 · 目标配比与再平衡
theme: jekyll-theme-cayman

# Keep webapp as static assets
exclude:
  - node_modules
  - scripts
  - templates
  - .github
  - package.json
  - package-lock.json
